import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
    {
        _id: uuid(),
        title: "Red Goggles",
        description: "Fox Racing Art",
        price: 3994,
        discountPercent: 15,
        categoryName: "goggles",
        source: "/Assets/Images/ProdImages/goggles-1.webp",
        alt: "Fox Racing Goggles",
        oneDayDelivery: false,
        outOfStock: false,
        rating: 5,
        isFeatured: true,
        badgeText: "best-seller",
    },
    {
        _id: uuid(),
        title: "BRAAAP",
        description: "100kmph X Sticker",
        price: 199,
        discountPercent: 5,
        categoryName: "stickers",
        source: "/Assets/Images/ProdImages/sticker-1.webp",
        alt: "100kmph X Sticker",
        fastDelivery: true,
        outOfStock: false,
        rating: 4,
        isFeatured: false,
        badgeText: "best-seller",
    },
    {
        _id: uuid(),
        title: "South Indian",
        description: "100kmph X Sticker",
        price: 199,
        categoryName: "stickers",
        source: "/Assets/Images/ProdImages/sticker-2.webp",
        alt: "100kmph X Sticker",
        fastDelivery: true,
        discountPercent: 5,
        outOfStock: false,
        rating: 3,
        isFeatured: false,
        badgeText: "new-arrival",
    },
    {
        _id: uuid(),
        title: "Horse Power",
        description: "100kmph X Sticker",
        price: 199,
        categoryName: "stickers",
        source: "/Assets/Images/ProdImages/sticker-3.webp",
        alt: "100kmph X Sticker",
        fastDelivery: false,
        discountPercent: 5,
        outOfStock: false,
        rating: 4,
        isFeatured: false,
        badgeText: "",
    },
    {
        _id: uuid(),
        title: "Tail Tidy",
        description: "97X Matt Black",
        price: 1299,
        categoryName: "tailtidy",
        source: "/Assets/Images/ProdImages/tailtidy-1.webp",
        alt: "Tail Tidy",
        fastDelivery: true,
        discountPercent: 10,
        outOfStock: true,
        rating: 4,
        isFeatured: false,
        badgeText: "",
    },
    {
        _id: uuid(),
        title: "B/W Goggles",
        description: "Fox Racing Art",
        price: 7999,
        discountPercent: 15,
        categoryName: "goggles",
        source: "/Assets/Images/ProdImages/goggles-2.webp",
        alt: "Fox Racing Goggles",
        oneDayDelivery: true,
        outOfStock: false,
        rating: 4,
        isFeatured: false,
        badgeText: "",
    },
    {
        _id: uuid(),
        title: "Wanderlust",
        description: "100kmph X Sticker",
        price: 149,
        categoryName: "stickers",
        source: "/Assets/Images/ProdImages/sticker-4.webp",
        alt: "100kmph X Sticker",
        fastDelivery: false,
        outOfStock: false,
        discountPercent: 20,
        rating: 4,
        isFeatured: false,
        badgeText: "new-arrival",
    },
    {
        _id: uuid(),
        title: "Liqui Moly",
        description: "100kmph X Sticker",
        price: 149,
        categoryName: "stickers",
        source: "/Assets/Images/ProdImages/sticker-6.webp",
        alt: "100kmph X Sticker",
        fastDelivery: false,
        outOfStock: false,
        rating: 4,
        isFeatured: true,
        badgeText: "best-seller",
        discountPercent: 50,
    },
    {
        _id: uuid(),
        title: "Pink Goggles",
        description: "Fox Racing Art",
        price: 4999,
        categoryName: "goggles",
        source: "/Assets/Images/ProdImages/goggles-3.webp",
        alt: "Fox Racing Goggles",
        oneDayDelivery: true,
        outOfStock: false,
        rating: 4,
        isFeatured: false,
        badgeText: "",
        discountPercent: 20,
    },
    {
        _id: uuid(),
        title: "Tail Tidy",
        description: "97X Carbon Fib-R",
        price: 2999,
        categoryName: "tailtidy",
        source: "/Assets/Images/ProdImages/tailtidy-2.webp",
        alt: "Tail Tidy",
        fastDelivery: false,
        outOfStock: false,
        rating: 4,
        isFeatured: true,
        badgeText: "new-arrival",
        discountPercent: 50,
    },
    {
        _id: uuid(),
        title: "Valentino Rossi",
        description: "100kmph X Sticker",
        price: 299,
        categoryName: "stickers",
        source: "/Assets/Images/ProdImages/sticker-7.webp",
        alt: "100kmph X Sticker",
        fastDelivery: true,
        outOfStock: false,
        rating: 4,
        isFeatured: true,
        badgeText: "best-seller",
        discountPercent: 20,
    },
    {
        _id: uuid(),
        title: "Spitified",
        description: "100kmph X Sticker",
        price: 199,
        categoryName: "stickers",
        source: "/Assets/Images/ProdImages/sticker-8.webp",
        alt: "100kmph X Sticker",
        fastDelivery: false,
        outOfStock: false,
        rating: 4,
        isFeatured: false,
        badgeText: "",
        discountPercent: 5,
    },
    {
        _id: uuid(),
        title: "Tinted Red Goggles",
        description: "Fox Racing Art",
        price: 5999,
        categoryName: "goggles",
        source: "/Assets/Images/ProdImages/goggles-4.webp",
        alt: "Fox Racing Goggles",
        oneDayDelivery: false,
        outOfStock: false,
        rating: 2,
        isFeatured: false,
        badgeText: "",
        discountPercent: 25,
    },
    {
        _id: uuid(),
        title: "Off-road Ambi",
        description: "100kmph X Sticker",
        price: 199,
        categoryName: "stickers",
        source: "/Assets/Images/ProdImages/sticker-9.webp",
        alt: "100kmph X Sticker",
        fastDelivery: false,
        outOfStock: false,
        rating: 4,
        isFeatured: false,
        badgeText: "",
        discountPercent: 30,
    },
    {
        _id: uuid(),
        title: "Tail Tidy",
        description: "97X Matt Red",
        price: 1899,
        categoryName: "tailtidy",
        source: "/Assets/Images/ProdImages/tailtidy-4.webp",
        alt: "Tail Tidy",
        fastDelivery: false,
        outOfStock: false,
        rating: 2,
        isFeatured: false,
        badgeText: "",
        discountPercent: 10,
    },
    {
        _id: uuid(),
        title: "Khardung La",
        description: "100kmph X Sticker",
        price: 199,
        categoryName: "stickers",
        source: "/Assets/Images/ProdImages/sticker-10.webp",
        alt: "100kmph X Sticker",
        fastDelivery: false,
        outOfStock: false,
        rating: 4,
        isFeatured: false,
        badgeText: "new-arrival",
        discountPercent: 20,
    },
    {
        _id: uuid(),
        title: "Tinted Black Goggles",
        description: "Fox Racing Art",
        price: 4999,
        categoryName: "goggles",
        source: "/Assets/Images/ProdImages/goggles-5.webp",
        alt: "Fox Racing Goggles",
        oneDayDelivery: false,
        outOfStock: false,
        rating: 5,
        isFeatured: false,
        badgeText: "best-seller",
        discountPercent: 40,
    },
    {
        _id: uuid(),
        title: "Drift",
        description: "100kmph X Sticker",
        price: 199,
        categoryName: "stickers",
        source: "/Assets/Images/ProdImages/sticker-11.webp",
        alt: "100kmph X Sticker",
        fastDelivery: false,
        outOfStock: false,
        rating: 4,
        isFeatured: false,
        badgeText: "",
        discountPercent: 5,
    },
    {
        _id: uuid(),
        title: "Kerala",
        description: "100kmph X Sticker",
        price: 199,
        categoryName: "stickers",
        source: "/Assets/Images/ProdImages/sticker-13.webp",
        alt: "100kmph X Sticker",
        fastDelivery: false,
        outOfStock: false,
        rating: 4,
        isFeatured: false,
        badgeText: "",
        discountPercent: 5,
    },
    {
        _id: uuid(),
        title: "Hyderabad",
        description: "100kmph X Sticker",
        price: 399,
        categoryName: "stickers",
        source: "/Assets/Images/ProdImages/sticker-14.webp",
        alt: "100kmph X Sticker",
        fastDelivery: false,
        outOfStock: false,
        rating: 5,
        isFeatured: false,
        badgeText: "",
        discountPercent: 20,
    },
    {
        _id: uuid(),
        title: "Magnetic Tidy",
        description: "97X Steel",
        price: 2999,
        categoryName: "tailtidy",
        source: "/Assets/Images/ProdImages/tailtidy-3.webp",
        alt: "Tail Tidy",
        fastDelivery: false,
        outOfStock: true,
        rating: 2,
        isFeatured: false,
        badgeText: "",
        discountPercent: 20,
    },
    {
        _id: uuid(),
        title: "Neon Goggles",
        description: "Fox Racing Art",
        price: 3999,
        categoryName: "goggles",
        source: "/Assets/Images/ProdImages/goggles-6.webp",
        alt: "Fox Racing Goggles",
        oneDayDelivery: false,
        outOfStock: false,
        rating: 3,
        isFeatured: false,
        badgeText: "",
        discountPercent: 10,
    },
];
