export const actionTypes = {
    SORT_BY_PRICE: "SORT_BY_PRICE",
    SLIDER_PRICE_VALUE: "SLIDER_PRICE_VALUE",
    RATING: "RATING",
    CATEGORY: "CATEGORY",
    EXCLUDE_OUT_OF_STOCK: "EXCLUDE_OUT_OF_STOCK",
    ONE_DAY_DELIVERY: "ONE_DAY_DELIVERY",
    PRODUCTS_INITIAL_RENDER: "PRODUCTS_INITIAL_RENDER",
    RESET_PRODUCT_FILTERS: "RESET_PRODUCT_FILTERS",
    SEARCH_PRODUCTS: "SEARCH_PRODUCTS",
};

export const signupErrorActionTypes = {
    SET_FIRSTNAME_ERROR: "SET_FIRSTNAME_ERROR",
    SET_LASTNAME_ERROR: "SET_LASTNAME_ERROR",
    SET_EMAIL_ERROR: "SET_EMAIL_ERROR",
    SET_PASSWORD_ERROR: "SET_PASSWORD_ERROR",
    SET_CONFIRM_PASSWORD_ERROR: "SET_CONFIRM_PASSWORD_ERROR",
    SET_AGREE_ERROR: "SET_AGREE_ERROR",
    RESET_SIGNUP_ERRORS: "RESET_SIGNUP_ERRORS",
};

export const signupUserActiontypes = {
    SET_FIRSTNAME: "SET_FIRSTNAME",
    SET_LASTNAME: "SET_LASTNAME",
    SET_EMAIL: "SET_EMAIL",
    SET_PASSWORD: "SET_PASSWORD",
    SET_CONFIRM_PASSWORD: "SET_CONFIRM_PASSWORD",
    SET_AGREE_TO: "SET_AGREE_TO",
    RESET_NEW_USER_DATA: "RESET_NEW_USER_DATA",
};

export const addressActionTypes = {
    SET_LOADING: "SET_LOADING",
    SET_ERROR: "SET_ERROR",
    SET_ADDRESS_LIST: "SET_ADDRESS_LIST",
};

export const addressFormActionTypes = {
    SET_NAME: "SET_NAME",
    SET_LOCALITY: "SET_LOCALITY",
    SET_CITY: "SET_CITY",
    SET_STATE: "SET_STATE",
    SET_PINCODE: "SET_PINCODE",
    SET_PHONE_NUMBER: "SET_PHONE_NUMBER",
    RESET_FORM: "RESET_FORM",
    SET_DUMMY_DATA: "SET_DUMMY_DATA",
};

export const addressFormErrorActionTypes = {
    SET_NAME_ERROR: "SET_NAME_ERROR",
    SET_LOCALITY_ERROR: "SET_LOCALITY_ERROR",
    SET_CITY_ERROR: "SET_CITY_ERROR",
    SET_PINCODE_ERROR: "SET_PINCODE_ERROR",
    SET_STATE_ERROR: "SET_STATE_ERROR",
    SET_NUMBER_ERROR: "SET_NUMBER_ERROR",
    RESET_ERRORS: "RESET_ERRORS",
};

export const orderActionTypes = {
    SET_LOADING: "SET_LOADING",
    SET_ERROR: "SET_ERROR",
    SET_ORDERS_LIST: "SET_ORDERS_LIST",
};
