 export const actionTypes={
    SORT_BY_PRICE:"SORT_BY_PRICE",
    SLIDER_PRICE_VALUE:"SLIDER_PRICE_VALUE",
    RATING:"RATING",
    CATEGORY:"CATEGORY",
    EXCLUDE_OUT_OF_STOCK:"EXCLUDE_OUT_OF_STOCK",
    ONE_DAY_DELIVERY:"ONE_DAY_DELIVERY",
    PRODUCTS_INITIAL_RENDER:"PRODUCTS_INITIAL_RENDER",
    RESET_PRODUCT_FILTERS:"RESET_PRODUCT_FILTERS"
}
