export const actionTypes = {
    SORT_BY_PRICE: "SORT_BY_PRICE",
    SLIDER_PRICE_VALUE: "SLIDER_PRICE_VALUE",
    RATING: "RATING",
    CATEGORY: "CATEGORY",
    EXCLUDE_OUT_OF_STOCK: "EXCLUDE_OUT_OF_STOCK",
    ONE_DAY_DELIVERY: "ONE_DAY_DELIVERY",
    PRODUCTS_INITIAL_RENDER: "PRODUCTS_INITIAL_RENDER",
    RESET_PRODUCT_FILTERS: "RESET_PRODUCT_FILTERS",
};

export const signupErrorActionTypes = {
    SET_FIRSTNAME_ERROR: "SET_FIRSTNAME_ERROR",
    SET_LASTNAME_ERROR: "SET_LASTNAME_ERROR",
    SET_EMAIL_ERROR: "SET_EMAIL_ERROR",
    SET_PASSWORD_ERROR:"SET_PASSWORD_ERROR",
    SET_CONFIRM_PASSWORD_ERROR:"SET_CONFIRM_PASSWORD_ERROR",
    SET_AGREE_ERROR:"SET_AGREE_ERROR",
    RESET_SIGNUP_ERRORS:"RESET_SIGNUP_ERRORS"
};

export const signupUserActiontypes={
    SET_FIRSTNAME:"SET_FIRSTNAME",
    SET_LASTNAME:"SET_LASTNAME",
    SET_EMAIL:"SET_EMAIL",
    SET_PASSWORD:"SET_PASSWORD",
    SET_CONFIRM_PASSWORD:"SET_CONFIRM_PASSWORD",
    SET_AGREE_TO:"SET_AGREE_TO",
    RESET_NEW_USER_DATA:"RESET_NEW_USER_DATA"
}